### ISSUE TITLE
Resolve the LilyPond command once at the boundary: buildScore re-reads LILYPOND_CMD inside every pool worker

### ISSUE THREAD

**Issue by wainwright1000** [wainwmr/spem-player#846]
## Symptom

`buildScores.mjs` resolves the LilyPond command from `process.env.LILYPOND_CMD` **deep inside itself**, once per call, from two independent places:

- `checkLilypond()` probes `--version` and gates the whole build on it being 2.26.0 or later.
- `buildScore()` calls `lilypondCommand()` **inside the render, inside the pool worker**, once per score.

So the build approves one command, then re-derives the command it actually runs from global mutable state, once per render. **The invariant that makes the version gate mean anything ("the binary whose `--version` we approved is the binary we render with") is never stated and never enforced.** It holds only because `main()` happens to call `checkLilypond()` before `runPool()`, and nothing in between writes `process.env`. That is an ordering accident doing the work of an invariant.

This is not a live bug and should not be filed as one. It is the structural reason #785 existed: the security suite had to *neutralise the world* to test anything, because `buildScore` is not a function of its arguments.

## The sharper consequence

`lilypondCommand()` calls `process.exit(1)` on a malformed override. Because it is called from inside `buildScore`, that exit is reachable **from within an in-flight async pool worker**. A `process.exit` there would tear the process down mid-render, bypassing `runPool`'s fail-fast accounting and bypassing `buildScore`'s own catch, which exists specifically to remove the half-written raw and stale final SVGs.

It cannot fire today, because `checkLilypond()` runs first and would already have exited on the same malformed value. Reorder `main()`, or add a second caller of the exported `buildScore`, and you get a mid-build abort with a partially written output tree.

## Recommended fix

Resolve the command **once, at the boundary**, and pass it down. The file already draws this line: it documents per-job state (`RenderJob`) as distinct from run-global state (`version`, `outDirBase`, "closed over"). The command is run-global and belongs in the same place.

```js
/** @typedef {readonly [string, ...string[]]} LilypondCmd */
/** @typedef {{ version: string, outDirBase: string, cmd: LilypondCmd }} RunConfig */

function lilypondCommand() { /* unchanged: reads process.env, validates, exits */ }

/** @param {LilypondCmd} cmd */
function checkLilypond(cmd) { ... }

/** @param {RenderJob} job @param {RunConfig} config */
async function buildScore(job, config) { ... }
```

and `main()`:

```js
const cmd = lilypondCommand();   // the ONE read of process.env, at the boundary
checkLilypond(cmd);              // probes exactly the command we will render with
await runPool(jobs, (job) => buildScore(job, { version, outDirBase, cmd }), renderConcurrency());
```

Why this is the smallest version and not a gold-plate:

- **`LILYPOND_CMD` stays.** It is the process-boundary contract (`doc/BUILD.md`), and it is load-bearing: the integration suite injects its fake LilyPond by putting `LILYPOND_CMD` in a *spawned child's* env, and a subprocess cannot take a JavaScript parameter. Any refactor that deletes the env var breaks that injection channel. What changes is that it is read **once**, in `main()`, and nothing below `main()` touches global state.
- It does not lengthen the argument list. `buildScore` already takes five positionals; folding to `(job, config)` takes it to two, using a boundary the file already documents. Roughly +4/-2 production lines.
- The `process.exit` inside `lilypondCommand()` becomes structurally unreachable from the pool, because the pool no longer calls it. No conversion to a throw needed.
- Test churn inverts: the security suite deletes its env-stubbing apparatus and passes an argument instead. Stubbing the world becomes passing a value.

**Do not** thread an `env` parameter through, or introduce a `LilypondCommand` class with a factory. For a build script that is over-engineering.

## Two type findings, worth taking even if the refactor is declined

**1. `lilypondCommand()` has no return type, in a package that type-checks.** `packages/scores` runs `tsc --noEmit` as `check:types`, and `parsed` comes from `JSON.parse`, so it is `any`. The non-empty-tuple invariant, the single thing that makes `const [bin, ...prefix] = lilypondCommand()` safe, is invisible to the compiler. Add:

```js
/** @typedef {readonly [string, ...string[]]} LilypondCmd */
/** @returns {LilypondCmd} */
```

Then `bin` types as `string`, not `string | undefined`, and any future edit that could return `[]` fails at the boundary rather than at `execFile` time deep in a parallel render. The runtime check stays: it is validating a JSON string from the environment, which no type system can do. Its role changes from "the only thing between an empty array and a broken execFile" to "the validator that produces the type".

**2. `[""]` passes validation and produces a misleading diagnostic.** `parsed.every((s) => typeof s === "string")` admits the empty string. `execFile("", ["--version"])` throws ENOENT, which `checkLilypond` reports as **"Error: lilypond is not installed or not on PATH"**. That sends a developer to inspect their `PATH` when their `LILYPOND_CMD` is the problem. Tighten to `typeof s === "string" && s.length > 0`, with a message naming `LILYPOND_CMD`. One line.

## Classification

**Tech debt (Maintainable), not a bug.** It removes a specific way the code is easy to use wrongly (calling `buildScore` and silently getting a different binary from the one `checkLilypond` approved) and replaces an ordering accident with a structural guarantee. Note that `tests-local/what-is-a-bug.md` Q7 weights maintainability lower for build/tooling code than app code (Mark's steer, #630), so this rides along with the next work in `buildScores.mjs` rather than justifying a standalone push.

## Provenance

#785 Vera gate (cycle 1, 2026-07-14), `spem-type-design-analyzer`. Deliberately not folded into #785: that ticket is test-only and this is a production refactor of a file the branch does not touch.

- CLAUDE

**Comment by wainwright1000** [comment]
Closed after cold adjudication (2026-07-14): demoted to the refactor report.

The cold smell-weigher returned qualifying-but-ride-along (Q7 only, area-weighted down for build tooling per Mark's #630 steer), agreeing with this ticket's own Classification paragraph, which already concluded it "rides along with the next work in buildScores.mjs rather than justifying a standalone push". Every technical claim verified against origin/main before demotion (the per-worker re-read at `:400`, the pool-reachable `process.exit`, the `[""]` validation gap at `:220`).

All three findings are now recorded in `wiki/refactor-buildScores.mjs.md` (Tech Debt items 8, 9 and 10): the boundary-resolution refactor, the missing `@returns` type on `lilypondCommand()`, and the empty-string validation gap. They ride with the next touch of the file.

- Vera

**Comment by wainwright1000** [comment]
## Reopened: this was closed under a rule that has since been withdrawn

Reopening on Andrew's instruction, 2026-07-21.

This ticket was closed `not_planned` on 2026-07-14 with the reason:

> The cold smell-weigher returned qualifying-but-ride-along (Q7 only,
> area-weighted down for build tooling per Mark's #630 steer) ... demoted to the
> refactor report.

That verdict no longer exists. Item
[#1414](https://github.com/wainwright1000/spem-tools/issues/1414) established
that the "qualifying but not worth a ticket" test was a duplicate of a size bar
already inside each of Q5, Q6 and Q7, added on 2026-06-16 with no author and no
item number. Andrew withdrew it on 2026-07-21.

The #630 half of that reasoning also does not survive as stated. Area weighting
applies to Q7 only, and it weights the argument; it does not negate a Q7 match.
Re-judged on 2026-07-21, this finding returned **`ticketable`**, Q7,
`build-tooling` weight: the weighting held, and the verdict changed anyway,
because the down-weighting never had the power to decline a match.

The finding (`refactor-buildScores.mjs.md` tech-debt item 8) is unchanged:
`lilypondCommand()`'s `process.exit(1)` is reachable from inside an in-flight
pool worker if `main()` is reordered or the exported `buildScore` gains a second
caller, bypassing the pool's fail-fast accounting. The fix shape is unchanged
too: resolve once in `main()` and pass it down as a run-config argument.

**Related work:** open ticket
[#785](https://github.com/wainwmr/spem-player/issues/785) makes the scores
security suite hermetic against an ambient `LILYPOND_CMD`. The root causes
differ, but this ticket's fix stops `buildScore` reading the environment at all,
which is what #785 needs, so the two should be sequenced together.

- CLAUDE

**Comment by wainwright1000** [comment]
## Re-specification (2026-07-24)

Re-specified on Andrew's instruction. Every claim re-verified against `origin/main` at `7ab6e46`. The finding and fix shape stand; this delta records the current line map, a newly-surfaced overlap with #890, the sequencing with #785, and the now-set Difficulty.

### Currency: all claims hold, with the current line map

The body's prose and `refactor-buildScores.mjs.md` item 8 are accurate; the exact locations on `7ab6e46` are:

- `lilypondCommand()` at `:210-225`. Its `process.exit(1)` calls are at `:218` (JSON parse failure) and `:222` (not a non-empty string array). The empty-string validation gap (finding 2 below) is the `parsed.every((s) => typeof s === "string")` at `:220`.
- `checkLilypond(version)` at `:227`. It calls `lilypondCommand()` at `:230`. The `version` parameter is never read (see the #890 note below).
- `buildScore(ly, version, notation, maxLyMtime, outDirBase)` at `:369` (five positionals). The per-worker `lilypondCommand()` call is at `:400`, inside the render, inside the pool worker.
- `main()` at `:449` runs `checkLilypond(version)` at `:456`, then `runPool(jobs, (job) => buildScore(job.ly, version, job.notation, job.maxLyMtime, outDirBase), ...)` at `:491-494`. The ordering accident the ticket describes is real and current.
- `buildScore` is exported at `~:515`.

### New: this ticket subsumes #890

Open ticket #890 (`.WS1`, ready to work) drops the unused `version` parameter from `checkLilypond`. This ticket's fix **replaces** that same `version` parameter with the resolved `cmd`, so removing `version` is a side effect of #846. The two tickets both change `checkLilypond`'s signature and will collide if worked independently.

Recommendation (Andrew's call, since #890 was just specified): close #890 as subsumed by #846, or sequence #890 first (a trivial removal) and let #846 add `cmd` to the then-parameterless `checkLilypond`. Left as-is they conflict.

### Sequencing with #785 (reaffirmed)

#846's fix stops `buildScore` reading `process.env` at all, which is exactly what open ticket #785 (make the scores security suite hermetic against an ambient `LILYPOND_CMD`) needs. Sequence together: #846 lands the boundary resolution, #785 then relies on it. Recommend recording #785 as `blocked-by #846`.

### Difficulty: M (was unset)

Small in production (roughly +4/-2 lines), but `buildScore`'s signature change from five positionals to `(job, config)` ripples to every caller: `main()` plus the `buildScores.integration.test.ts`, `buildScores.security.test.ts`, and `buildScores.test.ts` suites. The security suite additionally inverts about 12 env-stubbing sites to argument-passing. That cross-file test churn plus the #785/#890 coordination places it at M, not S.

### Fold (RR-fold)

- **Folded (already in the body):** finding 1, the missing `@returns` type on `lilypondCommand()` (`:210`), and finding 2, the `LILYPOND_CMD='[""]'` validation gap (`:220`). Both are in `lilypondCommand`, squarely in the boundary refactor's enclosing unit.
- **Deferred:** the ex-#786 bare `rmSync` in `buildScore`'s failure `catch` (guarded twin a few lines below). Same function, but outside the hunks the boundary refactor touches; it stays refactor-report-only and folds when the catch itself is edited.

### Test plan (delta)

- The security suite drops its env-stubbing and passes `cmd` as a `config` argument. Test churn inverts from stubbing the world to passing a value.
- Add a case asserting `buildScore` renders with the `cmd` it was passed (observable via the spawned binary), not one re-derived from `process.env`.
- Finding 2: add an `LILYPOND_CMD='[""]'` rejection case, asserting the message names `LILYPOND_CMD` rather than reporting a missing binary.
- Finding 1 is compile-time: `check:types` (`tsc --noEmit`) fails on any edit that could return `[]` from `lilypondCommand()`.
- Keep the existing version-gate test; the fix does not change the gate, only what it probes.

### Classification (confirmed)

Tech Debt, Q7 maintainable, build-tooling weight, ticketable per the 2026-07-21 re-judge. Real, not broken (the pool-reachable `process.exit` cannot fire today because `checkLilypond` exits first on the same input). The cold Q1/Q2 verifier was not re-run: the claim is not-broken, so there is no warm over-claim of broken-ness for the cold gate to remove, and the finding was already cold-adjudicated twice (Vera's close verification, and the 2026-07-21 re-judge). Trust labels: `vera...` (production refactor of a build-critical file, async and error-handling code) and `UI skip` (nothing user-visible changes).

- CLAUDE
